services:
  - type: web
    name: enhanced-av-asr
    env: python
    plan: starter  # 무료 티어
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: HF_HOME
        value: /tmp/huggingface
      - key: WAV2VEC2_MODEL_NAME
        value: facebook/wav2vec2-base
      - key: WHISPER_MODEL_NAME
        value: openai/whisper-base
      - key: AUDIO_WEIGHT
        value: 0.7
    disk:
      name: model-cache
      mountPath: /tmp
      sizeGB: 1
