services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter

    buildCommand: |
      set -euo pipefail
      echo "=== BUILD: deps ==="
      apt-get update && apt-get install -y wget curl git execstack && rm -rf /var/lib/apt/lists/*

      echo "=== 파이썬 의존성 설치 ==="
      pip install --no-cache-dir -r requirements.txt

      echo "=== ORT execstack 플래그 제거 ==="
      pybind_path=$(python -c 'import onnxruntime.capi._pybind_state as s; print(s.__file__)')
      echo "pybind so: $pybind_path"
      execstack -q "$pybind_path" || true
      execstack -c "$pybind_path" || true

      so_dir=$(python -c 'import pathlib, onnxruntime.capi._pybind_state as s; print(pathlib.Path(s.__file__).parent)')
      echo "patch all so in: $so_dir"
      find "$so_dir" -maxdepth 1 -type f -name "*.so*" -print -exec execstack -c {} \; || true

      echo "=== BUILD: download ONNX into /app/onnx ==="
      mkdir -p /app/onnx
      BASE_URL="${ONNX_ZIP_URL:-}"
      echo "ONNX_ZIP_URL=$BASE_URL"
      if [ -z "$BASE_URL" ]; then
        echo "ERROR: ONNX_ZIP_URL is empty"; exit 1
      fi
      for f in model.onnx model.int8.onnx config.json tokenizer.json; do
        echo "DL: $BASE_URL/$f -> /app/onnx/$f"
        if ! wget -q --show-progress -nc "$BASE_URL/$f" -O "/app/onnx/$f"; then
          echo "wget failed, trying curl: $f"
          curl -fL "$BASE_URL/$f" -o "/app/onnx/$f"
        fi
      done
      ls -la /app/onnx


    startCommand: |
      bash -lc '
        set -euo pipefail
        echo "=== START PATCH: clear execstack on ORT .so (no-import)==="

        # runtime 컨테이너에도 execstack 설치 (빌드/런타임 분리 대비)
        apt-get update && apt-get install -y execstack >/dev/null 2>&1 || true

        SITE_PKGS=$(python -c "import site,sys; print((site.getsitepackages() or [sys.prefix])[0])")
        ORT_CAPIDIR="$SITE_PKGS/onnxruntime/capi"
        echo "site-packages: $SITE_PKGS"
        echo "onnxruntime/capi: $ORT_CAPIDIR"

        if [ -d "$ORT_CAPIDIR" ]; then
          echo "[BEFORE] execstack flags:"
          (execstack -q "$ORT_CAPIDIR"/*.so* || true)
          # 플래그 제거
          find "$ORT_CAPIDIR" -maxdepth 1 -type f -name "*.so*" -exec execstack -c {} \; || true
          echo "[AFTER] execstack flags:"
          (execstack -q "$ORT_CAPIDIR"/*.so* || true)
        else
          echo "WARN: $ORT_CAPIDIR not found, skip execstack patch"
        fi

        echo "=== START SERVER ==="
        uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
      '



    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"
      - key: ONNX_MODEL_PATH
        value: "/app/onnx"          # ← 중요
      - key: ONNX_STORAGE_ROOT
        value: "/app/onnx"          # ← 중요
      - key: ONNX_ZIP_URL
        value: "https://github.com/Seoyoung0519/LipSee/releases/download/v1.0.0"
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"
      - key: USE_BATCH
        value: "false"

    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
