services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter

    buildCommand: |
      set -euo pipefail
      echo "=== BUILD: deps ==="
      apt-get update && apt-get install -y wget curl git && rm -rf /var/lib/apt/lists/*
      pip install --no-cache-dir -r requirements.txt
      echo "=== BUILD: download ONNX into /app/onnx ==="
      mkdir -p /app/onnx
      BASE_URL="${ONNX_ZIP_URL:-}"
      echo "ONNX_ZIP_URL=$BASE_URL"
      if [ -z "$BASE_URL" ]; then
        echo "ERROR: ONNX_ZIP_URL is empty"; exit 1
      fi
      for f in model.onnx model.int8.onnx config.json tokenizer.json; do
        echo "DL: $BASE_URL/$f -> /app/onnx/$f"
        if ! wget -q --show-progress -nc "$BASE_URL/$f" -O "/app/onnx/$f"; then
          echo "wget failed, trying curl: $f"
          curl -fL "$BASE_URL/$f" -o "/app/onnx/$f"
        fi
      done
      echo "=== BUILD: list /app/onnx ==="
      ls -la /app/onnx

    startCommand: |
      bash -lc '
        set -euo pipefail
        echo "=== START: ensure /app/onnx exists & files present ==="
        mkdir -p /app/onnx
        BASE_URL="${ONNX_ZIP_URL:-}"
        NEED_DL=false
        [ -f /app/onnx/model.onnx ] || NEED_DL=true
        if $NEED_DL; then
          echo "model.onnx not found; downloading at start"
          if [ -z "$BASE_URL" ]; then echo "ERROR: ONNX_ZIP_URL empty"; exit 1; fi
          for f in model.onnx model.int8.onnx config.json tokenizer.json; do
            [ -f "/app/onnx/$f" ] && { echo "skip existing $f"; continue; }
            echo "DL: $BASE_URL/$f -> /app/onnx/$f"
            if ! wget -q --show-progress -nc "$BASE_URL/$f" -O "/app/onnx/$f"; then
              echo "wget failed, trying curl: $f"
              curl -fL "$BASE_URL/$f" -o "/app/onnx/$f"
            fi
          done
        else
          echo "models already exist; skipping download"
        fi
        echo "=== START: list /app/onnx ==="
        ls -la /app/onnx || true
        echo "=== START: launch uvicorn ==="
        uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
      '

    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"
      - key: ONNX_MODEL_PATH
        value: "/app/onnx"          # ← 중요
      - key: ONNX_STORAGE_ROOT
        value: "/app/onnx"          # ← 중요
      - key: ONNX_ZIP_URL
        value: "https://github.com/Seoyoung0519/LipSee/releases/download/v1.0.0"
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"
      - key: USE_BATCH
        value: "false"

    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
