services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      # Google Drive에서 ONNX 모델 파일 다운로드
      apt-get update && apt-get install -y wget
      mkdir -p onnx
      # Google Drive에서 ONNX 모델 파일들 개별 다운로드
      # model.int8.onnx: https://drive.google.com/file/d/1OVytw_Rbh0zjkkjfjkAEWgTUxluFmYIh/view?usp=drive_link
      # config.json: https://drive.google.com/file/d/1lpddoLZOzXKGpEinMCx3kx8kg2c3lPgp/view?usp=drive_link
      # tokenizer.json: https://drive.google.com/file/d/1e0FHSh0dUqpI1n_ibhFusyvUgjtzi-Eu/view?usp=drive_link
      gdown "https://drive.google.com/uc?id=1OVytw_Rbh0zjkkjfjkAEWgTUxluFmYIh" -O /app/onnx/model.int8.onnx
      gdown "https://drive.google.com/uc?id=1lpddoLZOzXKGpEinMCx3kx8kg2c3lPgp" -O /app/onnx/config.json
      gdown "https://drive.google.com/uc?id=1e0FHSh0dUqpI1n_ibhFusyvUgjtzi-Eu" -O /app/onnx/tokenizer.json
      echo "ONNX 모델 파일들 다운로드 완료"
      # 다운로드된 파일들 확인
      ls -la /app/onnx/
      echo "현재 작업 디렉토리: $(pwd)"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"  # ONNX 모델 사용
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"  # 원래 값으로 복원
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "/app/onnx"  # ONNX 모델 폴더 절대 경로
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
