services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      set -euo pipefail
      echo "=== 빌드 시작 ==="
      echo "현재 디렉토리: $(pwd)"
      python --version || true

      echo "=== 시스템 패키지 설치 ==="
      apt-get update && apt-get install -y wget curl unzip git && rm -rf /var/lib/apt/lists/*

      echo "=== 파이썬 의존성 설치 ==="
      pip install --no-cache-dir -r requirements.txt
      pip install --no-cache-dir gdown

      echo "=== ONNX 모델 다운로드 ==="
      mkdir -p /app/onnx
      echo "ONNX_ZIP_URL: ${ONNX_ZIP_URL:-}"
      echo "MODEL_TYPE: ${MODEL_TYPE:-}"

      if [ -n "${ONNX_ZIP_URL:-}" ]; then
        BASE_URL="${ONNX_ZIP_URL}"
        FILES=("model.onnx" "model.int8.onnx" "config.json" "tokenizer.json")
        echo "기본 URL: $BASE_URL"
        for file in "${FILES[@]}"; do
          echo "다운로드: $BASE_URL/$file -> /app/onnx/$file"
          if ! wget -q --show-progress "$BASE_URL/$file" -O "/app/onnx/$file"; then
            echo "wget 실패, curl 재시도: $file"
            curl -fL "$BASE_URL/$file" -o "/app/onnx/$file"
          fi
        done
        echo "다운로드된 파일:"
        ls -la /app/onnx
      else
        echo "ERROR: ONNX_ZIP_URL 미설정"
        exit 1
      fi

      echo "=== 빌드 완료 ==="
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "/app/onnx"              # ← 변경
      - key: ONNX_STORAGE_ROOT
        value: "/app/onnx"              # ← 변경
      - key: ONNX_ZIP_URL
        value: "https://github.com/Seoyoung0519/LipSee/releases/download/v1.0.0"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
