services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter

    buildCommand: |
      set -euo pipefail
      echo "=== BUILD: deps ==="
      apt-get update && apt-get install -y wget curl git execstack && rm -rf /var/lib/apt/lists/*

      echo "=== 파이썬 의존성 설치 ==="
      pip install --no-cache-dir -r requirements.txt

      echo "=== ORT execstack 플래그 제거 ==="
      pybind_path=$(python -c 'import onnxruntime.capi._pybind_state as s; print(s.__file__)')
      echo "pybind so: $pybind_path"
      execstack -q "$pybind_path" || true
      execstack -c "$pybind_path" || true

      so_dir=$(python -c 'import pathlib, onnxruntime.capi._pybind_state as s; print(pathlib.Path(s.__file__).parent)')
      echo "patch all so in: $so_dir"
      find "$so_dir" -maxdepth 1 -type f -name "*.so*" -print -exec execstack -c {} \; || true

      echo "=== BUILD: download ONNX into /app/onnx ==="
      mkdir -p /app/onnx
      BASE_URL="${ONNX_ZIP_URL:-}"
      echo "ONNX_ZIP_URL=$BASE_URL"
      if [ -z "$BASE_URL" ]; then
        echo "ERROR: ONNX_ZIP_URL is empty"; exit 1
      fi
      for f in model.onnx model.int8.onnx config.json tokenizer.json; do
        echo "DL: $BASE_URL/$f -> /app/onnx/$f"
        if ! wget -q --show-progress -nc "$BASE_URL/$f" -O "/app/onnx/$f"; then
          echo "wget failed, trying curl: $f"
          curl -fL "$BASE_URL/$f" -o "/app/onnx/$f"
        fi
      done
      ls -la /app/onnx


    startCommand: |
      bash -lc '
        set -euo pipefail
        echo "=== START MARK === (should appear at boot)"
        mkdir -p /app/onnx
        BASE_URL="${ONNX_ZIP_URL:-}"
        echo "ONNX_MODEL_PATH=${ONNX_MODEL_PATH:-}"
        echo "ONNX_ZIP_URL=${BASE_URL}"

        FILES=("model.onnx" "model.int8.onnx" "config.json" "tokenizer.json")

        NEED_DL=false
        [ -f /app/onnx/model.onnx ] || NEED_DL=true

        if $NEED_DL; then
          if [ -z "$BASE_URL" ]; then
            echo "ERROR: ONNX_ZIP_URL empty"; exit 1
          fi
          for f in "${FILES[@]}"; do
            [ -f "/app/onnx/$f" ] && { echo "skip existing $f"; continue; }
            echo "DL: $BASE_URL/$f -> /app/onnx/$f"
            if ! wget -q --show-progress -nc "$BASE_URL/$f" -O "/app/onnx/$f"; then
              echo "wget failed, trying curl: $f"
              curl -fL "$BASE_URL/$f" -o "/app/onnx/$f"
            fi
          done
        else
          echo "models exist; skip download"
        fi

        echo "=== LIST /app/onnx ==="
        ls -la /app/onnx || true

        echo "=== UVICORN ==="
        uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
      '


    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"
      - key: ONNX_MODEL_PATH
        value: "/app/onnx"          # ← 중요
      - key: ONNX_STORAGE_ROOT
        value: "/app/onnx"          # ← 중요
      - key: ONNX_ZIP_URL
        value: "https://github.com/Seoyoung0519/LipSee/releases/download/v1.0.0"
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"
      - key: USE_BATCH
        value: "false"

    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
