services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      # Google Drive에서 ONNX 모델 파일 다운로드
      apt-get update && apt-get install -y wget
      mkdir -p onnx
      # Google Drive에서 ONNX 모델 파일들 다운로드
      # 폴더 링크: https://drive.google.com/drive/folders/1Gx2LdUJ95hLjCddjr_wbQdY10pJ_owSR
      gdown "https://drive.google.com/uc?id=1Gx2LdUJ95hLjCddjr_wbQdY10pJ_owSR" --folder -O onnx/
      echo "ONNX 모델 파일들 다운로드 완료"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"  # ONNX 모델 사용
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"  # 원래 값으로 복원
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "./onnx"  # ONNX 모델 폴더 경로
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
