services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      echo "=== 빌드 시작 ==="
      echo "현재 디렉토리: $(pwd)"
      echo "Python 버전: $(python --version)"
      
      echo "=== 의존성 설치 시작 ==="
      pip install -r requirements.txt
      echo "의존성 설치 완료"
      
      echo "=== 시스템 패키지 설치 시작 ==="
      apt-get update && apt-get install -y wget unzip curl git
      echo "시스템 패키지 설치 완료"
      
      echo "=== gdown 설치 시작 ==="
      pip install gdown
      echo "gdown 설치 완료"
      
      echo "=== ONNX 모델 다운로드 준비 ==="
      mkdir -p /var/data/onnx
      echo "ONNX 디렉토리 생성: /var/data/onnx"
      
      # 환경변수 확인
      echo "ONNX_ZIP_URL: $ONNX_ZIP_URL"
      echo "MODEL_TYPE: $MODEL_TYPE"
      
              if [ -n "$ONNX_ZIP_URL" ]; then
          echo "=== 개별 ONNX 모델 파일 다운로드 시작 ==="
          
          # GitHub Releases URL에서 기본 경로 추출
          BASE_URL="$ONNX_ZIP_URL"
          echo "기본 URL: $BASE_URL"
          
          # 개별 파일들 다운로드
          FILES=("model.onnx" "model.int8.onnx" "config.json" "tokenizer.json")
          DOWNLOAD_SUCCESS=true
          
          for file in "${FILES[@]}"; do
            echo "다운로드 중: $file"
            if wget --progress=bar:force:noscroll "$BASE_URL/$file" -O "/var/data/onnx/$file"; then
              echo "✅ $file 다운로드 성공"
            else
              echo "❌ $file 다운로드 실패"
              DOWNLOAD_SUCCESS=false
            fi
          done
          
          if [ "$DOWNLOAD_SUCCESS" = true ]; then
            echo "모든 파일 다운로드 성공"
            echo "=== 다운로드된 파일 목록 ==="
            ls -la /var/data/onnx/
            echo "=== 파일 개수 ==="
            find /var/data/onnx/ -type f | wc -l
            
            echo "=== /app/onnx 폴더에도 복사 ==="
            mkdir -p /app/onnx
            cp -r /var/data/onnx/* /app/onnx/
            echo "복사 완료: /app/onnx"
            ls -la /app/onnx/
          else
            echo "ERROR: 일부 파일 다운로드 실패"
            exit 1
          fi
      else
        echo "ERROR: ONNX_ZIP_URL 환경변수가 설정되지 않음"
        exit 1
      fi
      
      echo "=== 빌드 완료 ==="
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"  # ONNX 모델 사용
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"  # 원래 값으로 복원
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "/var/data/onnx"  # ONNX 모델 폴더 절대 경로
      - key: ONNX_STORAGE_ROOT
        value: "/var/data/onnx"  # ONNX 저장소 루트
      - key: ONNX_ZIP_URL
        value: "https://github.com/Seoyoung0519/LipSee/releases/download/v1.0.0"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
