services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      # ONNX 모델 파일 확인 (사전 다운로드 불필요)
      echo "ONNX 모델 사용 - 별도 다운로드 불필요"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"  # ONNX 모델 사용
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"  # 원래 값으로 복원
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "./onnx"  # ONNX 모델 폴더 경로
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
