services:
  - type: web
    name: lipsee-emotion-api
    env: python
    plan: starter
    buildCommand: |
      echo "=== 빌드 시작 ==="
      echo "현재 디렉토리: $(pwd)"
      echo "Python 버전: $(python --version)"
      
      echo "=== 의존성 설치 시작 ==="
      pip install -r requirements.txt
      echo "의존성 설치 완료"
      
      echo "=== 시스템 패키지 설치 시작 ==="
      apt-get update && apt-get install -y wget unzip curl git
      echo "시스템 패키지 설치 완료"
      
      echo "=== gdown 설치 시작 ==="
      pip install gdown
      echo "gdown 설치 완료"
      
      echo "=== ONNX 모델 다운로드 준비 ==="
      mkdir -p /var/data/onnx
      echo "ONNX 디렉토리 생성: /var/data/onnx"
      
      # 환경변수 확인
      echo "ONNX_ZIP_URL: $ONNX_ZIP_URL"
      echo "MODEL_TYPE: $MODEL_TYPE"
      
      if [ -n "$ONNX_ZIP_URL" ]; then
        echo "=== ONNX ZIP 다운로드 시작 ==="
        echo "다운로드 URL: $ONNX_ZIP_URL"
        
        # Google Drive ID 추출
        DRIVE_ID=$(echo "$ONNX_ZIP_URL" | grep -o '[a-zA-Z0-9_-]\{33,\}' | head -1)
        echo "추출된 Drive ID: $DRIVE_ID"
        
        if [ -n "$DRIVE_ID" ]; then
          echo "=== gdown으로 다운로드 시도 ==="
          if gdown "https://drive.google.com/uc?id=$DRIVE_ID" -O /tmp/onnx_models.zip; then
            echo "ZIP 다운로드 성공 (gdown)"
            echo "파일 크기: $(ls -lh /tmp/onnx_models.zip)"
            
            echo "=== 압축 해제 시작 ==="
            if unzip -o /tmp/onnx_models.zip -d /var/data/onnx/; then
              echo "압축 해제 성공"
              echo "=== 압축 해제된 파일 목록 ==="
              ls -la /var/data/onnx/
              echo "=== 파일 개수 ==="
              find /var/data/onnx/ -type f | wc -l
            else
              echo "ERROR: 압축 해제 실패"
              exit 1
            fi
            
            echo "=== 임시 파일 정리 ==="
            rm -f /tmp/onnx_models.zip
            echo "정리 완료"
          else
            echo "ERROR: gdown 다운로드 실패, wget으로 재시도"
            if wget --progress=bar:force:noscroll "$ONNX_ZIP_URL" -O /tmp/onnx_models.zip; then
              echo "ZIP 다운로드 성공 (wget)"
              echo "파일 크기: $(ls -lh /tmp/onnx_models.zip)"
              
              echo "=== 압축 해제 시작 ==="
              if unzip -o /tmp/onnx_models.zip -d /var/data/onnx/; then
                echo "압축 해제 성공"
                echo "=== 압축 해제된 파일 목록 ==="
                ls -la /var/data/onnx/
                echo "=== 파일 개수 ==="
                find /var/data/onnx/ -type f | wc -l
              else
                echo "ERROR: 압축 해제 실패"
                exit 1
              fi
              
              echo "=== 임시 파일 정리 ==="
              rm -f /tmp/onnx_models.zip
              echo "정리 완료"
            else
              echo "ERROR: 모든 다운로드 방법 실패"
              echo "wget 종료 코드: $?"
              exit 1
            fi
          fi
        else
          echo "ERROR: Google Drive ID를 추출할 수 없음"
          exit 1
        fi
      else
        echo "ERROR: ONNX_ZIP_URL 환경변수가 설정되지 않음"
        exit 1
      fi
      
      echo "=== 빌드 완료 ==="
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: MODEL_TYPE
        value: "onnx"  # ONNX 모델 사용
      - key: SRT_DEFAULT_FILENAME
        value: "emotion_subtitles.srt"
      - key: MAX_LENGTH
        value: "128"  # 원래 값으로 복원
      - key: USE_BATCH
        value: "false"
      - key: ONNX_MODEL_PATH
        value: "/var/data/onnx"  # ONNX 모델 폴더 절대 경로
      - key: ONNX_STORAGE_ROOT
        value: "/var/data/onnx"  # ONNX 저장소 루트
      - key: ONNX_ZIP_URL
        value: "https://drive.google.com/uc?export=download&id=1_U_CzzD6wQKd9OLvcLj1ntE-tm4oJwTC"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
